enum class GrubbyTokenType {
    IMPORT, PRINTLN, LATER, VAR, VAL, FN, END, FOR, FOREACH, WHILE, IN, TO, ARRAY, STRING, NUMBER, IDENTIFIER, OPERATOR, COMMENT, BLOCK, EQUALS, IF, THEN, ELSE, ELSEIF, WHITESPACE
}